/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Point;
import java.util.Locale;
import javax.swing.ImageIcon;
import model.EmployeeModel;
import services.UserController;

/**
 *
 * @author ACER
 */
public class EmployeeeView extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeeView
     */
    private int x;
    private int y;
    private EmployeeModel employeeModel;
    private UserController controller;

    public EmployeeeView(EmployeeModel model,UserController controller) {
        this.controller = controller;
        this.employeeModel = model;
        initComponents();
        setComponents();
        frameSetting();
    }

    private void setComponents() {
        setLocationRelativeTo(null);
        String fullName =employeeModel.getUsername()+" "+employeeModel.getLast_name();
        fullName = fullName.toUpperCase(Locale.ENGLISH);
        nameOFEMployee.setText(fullName);
    }

    private void frameSetting() {
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/assets/iconLogo.png"));
        this.setIconImage(imageIcon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPane = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        frameBar = new javax.swing.JPanel();
        minLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameOFEMployee = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPane.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundPaneMouseDragged(evt);
            }
        });
        backgroundPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundPaneMousePressed(evt);
            }
        });
        backgroundPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo_small.png"))); // NOI18N
        backgroundPane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 19, 89, 34));

        frameBar.setBackground(new java.awt.Color(255, 255, 255));
        frameBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_minus_48px_1 1.png"))); // NOI18N
        minLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minLabel1MouseClicked(evt);
            }
        });
        frameBar.add(minLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        exitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exitButton.png"))); // NOI18N
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabeljLabel4MouseClicked(evt);
            }
        });
        frameBar.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 30, 30));

        backgroundPane.add(frameBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(778, 22, 82, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Saly-71.png"))); // NOI18N
        backgroundPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 92, 606, 578));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ellipse_4.png"))); // NOI18N
        backgroundPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 475, 475));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ellipse_5.png"))); // NOI18N
        backgroundPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 179, 398, 398));

        jLabel4.setFont(new java.awt.Font("Baloo Bhai", 0, 82)); // NOI18N
        jLabel4.setText("Hi!");
        backgroundPane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 218, -1, -1));

        nameOFEMployee.setFont(new java.awt.Font("Baloo Bhai", 0, 45)); // NOI18N
        nameOFEMployee.setForeground(new java.awt.Color(52, 65, 143));
        nameOFEMployee.setText("JOSH DOPE");
        backgroundPane.add(nameOFEMployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 309, -1, -1));

        logOut.setBackground(new java.awt.Color(1, 209, 143));
        logOut.setFont(new java.awt.Font("Baloo Bhai", 0, 25)); // NOI18N
        logOut.setForeground(new java.awt.Color(255, 255, 255));
        logOut.setText("SIGN OUT");
        logOut.setBorder(null);
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        backgroundPane.add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 384, 219, 46));

        getContentPane().add(backgroundPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        setBounds(0, 0, 900, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void minLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minLabel1MouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minLabel1MouseClicked

    private void exitLabeljLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabeljLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLabeljLabel4MouseClicked

    private void backgroundPaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundPaneMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_backgroundPaneMousePressed

    private void backgroundPaneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundPaneMouseDragged
        Point coord = evt.getLocationOnScreen();
        setLocation(coord.x - x, coord.y - y);
    }//GEN-LAST:event_backgroundPaneMouseDragged

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        dispose();
        new LoginView(controller).setVisible(true);
    }//GEN-LAST:event_logOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeeView(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPane;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JPanel frameBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton logOut;
    private javax.swing.JLabel minLabel;
    private javax.swing.JLabel nameOFEMployee;
    // End of variables declaration//GEN-END:variables
}
